#!/bin/sh

# Copy this file to ./.git/hooks/pre-commit

if [ -z "$(which sblint)" ]; then
    echo "WARNING! sblint not found. Given up to run it."
    exit 0
fi

error_count=$(sblint | wc -l | tr -d '[[:space:]]')

if [ "$error_count" -gt "0" ]; then
    echo "Failed to commit because $error_count errors are found by SBLint."
    exit 1
fi
